
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build exercise files and progress server
    init: gradle run distuebungenMarkdown
    command: gradle progress

  - name: Build website & Webserver on 4000
    init: ./run-website-build.sh
    command: ./run-server.sh

  - name: Übungen
    command: mkdir -p build/git-uebungen/aufgaben && cd build/git-uebungen/aufgaben && ls

ports:
  - port: 4000
    onOpen: ignore
  - port: 8040
    onOpen: open-preview
  - port: 8080
    onOpen: open-browser
    visibility: public

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - richardwillis.vscode-gradle
    - fwcd.kotlin
    - eamodio.gitlens
